global:
  wildcardCertName: cert-manager-ingress-cert

clusterGroup:
  name: prod

  namespaces:
    vault:
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    external-secrets:
    openshift-lws-operator:
      operatorGroup: true
      targetNamespaces:
        - openshift-lws-operator
    cert-manager-operator:
      operatorGroup: true
      targetNamespaces: []
    # keycloak:
    #   operatorGroup: true
    #   targetNamespaces:
    #     - keycloak
    redhat-ods-operator:
      operatorGroup: true
      targetNamespaces: []
    kuadrant-system:
    grafana:
    openshift-nfd:
    nvidia-gpu-operator:
    openshift-storage:
      operatorGroup: true
      targetNamespaces:
        - openshift-storage

  sharedValueFiles:
    - /overrides/values-{{ $.Values.global.clusterPlatform }}.yaml

  subscriptions:
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
    postgres:
      name: cloudnative-pg
      channel: stable-v1
      source: certified-operators
    devspaces:
      name: devspaces
    grafana:
      name: grafana-operator
      namespace: grafana
      channel: v5
      source: community-operators
    lws:
      name: leader-worker-set
      channel: stable-v1.0
    cert-manager:
      name: openshift-cert-manager-operator
      channel: stable-v1
    # keycloak:
    #   name: rhbk-operator
    #   channel: stable-v26.4
    kuadrant:
      name: rhcl-operator
    rhoai:
      name: rhods-operator
      channel: stable-3.3
    nfd:
      name: nfd
      namespace: openshift-nfd
    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      source: certified-operators
    lvms:
      name: lvms-operator
      namespace: openshift-storage

  applications:
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*
    image-registry:
      name: image-registry
      namespace: openshift-image-registry
      path: charts/image-registry
    lvms:
      name: lvms
      namespace: openshift-storage
      path: charts/lvms
    maas-scaffolding:
      name: maas-scaffolding
      path: charts/maas-scaffolding
    maas-quickstart:
      name: maas-quickstart
      repoURL: https://github.com/dminnear-rh/maas-code-assistant.git
      chartVersion: main
      path: charts/maas-code-assistant
      extraValueFiles:
        - /overrides/maas-quickstart.yaml

  imperative:
    jobs:
      - name: configure-registry-pull-secret
        playbook: ansible/playbooks/configure-registry-pull-secret.yml
        timeout: 300
