apiVersion: operator.openshift.io/v1
kind: LeaderWorkerSetOperator
metadata:
  name: cluster
  namespace: openshift-lws-operator
spec:
  logLevel: Normal
  managementState: Managed
  operatorLogLevel: Normal
