apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: htpasswd-secret-es
  namespace: openshift-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: htpasswd-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        htpasswd: |
          {{- range .Values.htpasswdUsers }}
          {{ printf `{{ htpasswd "%s" (index . "%s") }}` . . }}
          {{- end }}
  data:
  {{- range .Values.htpasswdUsers }}
  - secretKey: {{ . }}
    remoteRef:
      key: secret/data/hub/htpasswd
      property: {{ . }}
  {{- end }}
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: htpasswd_provider
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpasswd-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  {{- range .Values.clusterAdmins }}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ . }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-readers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
  {{- range .Values.clusterReaders }}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ . }}
  {{- end }}
