global:
  wildcardCertName: default-ingress-cert

htpasswdUsers:
  - admin
  - free-user
  - premium-user
  - enterprise-user

clusterAdmins:
  - admin
  - kubeadmin

clusterReaders:
  - free-user
  - premium-user
  - enterprise-user
